language: rust

INSTALL_NODE_VIA_NVM: &INSTALL_NODE_VIA_NVM
                        |
                        rustup target add wasm32-unknown-unknown
                        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash
                        source ~/.nvm/nvm.sh
                        nvm install 14.4.0

# Cache `cargo install`ed tools, but don't cache the project's `target`
# directory (which ends up over-caching and filling all disk space!)
cache:
  directories:
    - /home/travis/.cargo

matrix:
  include:

    - name: Tests
      rust: stable
      env:
        global:
          - RUST_BACKTRACE=1
          - MOZ_HEADLESS=1
      addons:
        firefox: latest
      install:
        - *INSTALL_NODE_VIA_NVM
        - export PATH="$PATH:$HOME/.cargo/bin"
        - rustup target add wasm32-unknown-unknown || true
        - rustup toolchain install nightly
        - yarn
        - wget https://github.com/emscripten-core/emsdk/archive/master.zip && unzip master.zip && ./emsdk-master/emsdk install latest && ./emsdk-master/emsdk activate latest
        - cargo +nightly install --git https://github.com/MTRNord/matrixclient-testsuite
      script:
        - source emsdk-master/emsdk_env.sh && yarn run build:dev
        - mxctest &
        - cargo test --all --locked

