[package]
name = "yew-wasm-pack-template"
version = "0.2.0"
authors = ["Yew Maintainers <maintainers@yew.rs"]
edition = "2018"
license = "AGPL-v3.0"
repository = "https://github.com/MTRNord/Daydream"
description = "A Matrix Web client written in Rust"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "0.1"
console_error_panic_hook = { version = "0.1", optional = true }
log = "0.4"
serde = { version = "1.0", features = ["rc", "derive"] }
serde_json = "1.0.53"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.12"
wasm-logger = "0.2"
wee_alloc = "0.4"
yew = { git = "https://github.com/yewstack/yew" }
yew-router = { git = "https://github.com/yewstack/yew" }
yewtil = { git = "https://github.com/yewstack/yew" }
matrix-sdk = { version = "0.1.0", git = "https://github.com/matrix-org/matrix-rust-sdk.git", default-features = false}
url = "2.1.1"
thiserror = "1.0"
futures-locks = { git = "https://github.com/asomers/futures-locks", default-features = false }
js_int = "0.1.5"
linked_hash_set = {version = "0.1.3", features = ["serde"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
  'KeyboardEvent',
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
