# (Required) The locale/language identifier of the language used in the source
# code.
src_locale = "en"

# (Required) The locales that the software will be translated into.
target_locales = ["de"]

[gettext]
# (Required) Path to the output directory, relative to `i18n.toml` of the crate
# being localized.
output_dir = "i18n"
