name: Test Daydream

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Setup Wasm Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: yarn

      - name: Get emscripten SDK
        run: wget https://github.com/emscripten-core/emsdk/archive/master.zip && unzip master.zip && ./emsdk-master/emsdk install latest && ./emsdk-master/emsdk activate latest

      - name: Build
        run: source emsdk-master/emsdk_env.sh && yarn run build:dev

      - name: Install matrix-test-server
        run: |
          cargo +nightly install --git https://github.com/MTRNord/matrixclient-testsuite
          mxctest &

      - name: Run tests
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          cargo test
